//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietDichVu
    {
        public int ID { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaDV { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual tblDichVu tblDichVu { get; set; }
        public virtual tblHoaDon tblHoaDon { get; set; }
    }
}
