//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDon
    {
        public int ID { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<decimal> DonGiaThucTe { get; set; }
        public Nullable<int> SoNgayO { get; set; }
    
        public virtual tblPhong tblPhong { get; set; }
        public virtual tblHoaDon tblHoaDon { get; set; }
    }
}
